# Generated by Django 6.1.1 on 2026-09-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('DATABASE', 'Base de données & Cloud'), ('TOOLS', 'Outils & Méthodologies')], max_length=20)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('subtitle', models.CharField(help_text='Ex: PWA de gestion / SPA E-commerce', max_length=255)),
                ('description', models.TextField(help_text='Problème résolu et valeur ajoutée du projet')),
                ('architecture_details', models.TextField(blank=True, help_text='Détails techniques (Ex: Auth JWT, PWA offline, REST API)')),
                ('image', models.ImageField(upload_to='projects/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Afficher en premier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(related_name='projects', to='mainapp.skill')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
